#ifndef VITAKI_FORK_VERSION_H
#define VITAKI_FORK_VERSION_H

// Auto-generated version information - DO NOT EDIT MANUALLY
#define VITAKI_FORK_VERSION_MAJOR 0
#define VITAKI_FORK_VERSION_MINOR 1
#define VITAKI_FORK_VERSION_PATCH 629
#define VITAKI_FORK_VERSION_STRING "0.1.629"

#endif // VITAKI_FORK_VERSION_H
